In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes

In [2]:
X, y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [6]:
from sklearn.linear_model import SGDRegressor
bGd = SGDRegressor(shuffle=False,learning_rate='constant',eta0=0.01)

In [8]:
epochs = 100
for epoch in range(epochs):
    bGd.partial_fit(X_train, y_train)

In [9]:
bGd.intercept_, bGd.coef_

(array([154.76127476]),
 array([  57.17438236,  -66.39425045,  346.64739245,  248.62016525,
          18.20155535,  -26.33319099, -171.40129853,  127.26050259,
         313.58558909,  127.04470959]))

In [10]:
y_pred = bGd.predict(X_test)

In [11]:
y_pred

array([156.86511807, 193.47137549, 142.86928288, 112.18854929,
       245.86533169, 238.23143133, 110.71113239, 117.76836159,
        96.60182022, 187.32798315, 163.01024471, 175.42436076,
       186.85244859, 153.52653448, 255.14834915,  96.02976222,
       187.82692686, 142.18341686, 142.78436634, 142.39153196,
       135.62470717, 192.00758589, 169.29177934, 180.59752126,
       129.79955202, 221.28738886, 197.4229477 , 124.26469232,
        67.28967117, 242.54732977, 237.5258406 , 122.69708724,
        78.61296242, 113.85284206, 201.54329521, 168.71896627,
       169.94512615, 198.31939684, 118.79836907, 234.63188939,
       138.88506584, 130.44866898, 187.24136265, 188.48950559,
       173.16181209, 148.78916175, 176.3879333 , 278.58436517,
       121.27742789, 191.50087103, 237.78289821, 133.44899092,
       146.62131072, 153.2686197 , 191.98184955, 117.45062173,
       158.98941112,  89.98198987, 161.5127939 , 146.44138477,
       166.73149966, 174.16676199, 114.55144105, 207.30

In [12]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.43145758231819464