In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

In [2]:
X, y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [11]:
class BatchGradientDescent:
    def __init__(self,learning_rate=0.1,epochs=100):
        self.learning_rate =learning_rate
        self.epochs =epochs
        self.coef =None
        self.intercept =None
        
    def fit(self,X_train,y_train):
        no_of_row = X_train.shape[0]
        no_of_col = X_train.shape[1]
        
        # 1. Initialize Intercept and Coef
        self.intercept = 0
        self.coef = np.ones(no_of_col)
        
        for epoch in range(self.epochs):
            
            y_hat = self.intercept + np.dot(X_train,self.coef)        # 0 + (row,col) dot (col,)  ---> (row,)
            
            # 2. Calculate Gradient
            dL_by_dB0 =  (-2 * np.sum(y_train - y_hat) )/ no_of_row
            dL_by_dB1 = (-2 * np.dot(y_train - y_hat, X_train)) / no_of_row    # (row,) * (row * col)  ---> (col,)
            
            # 3. Update Intercept and Coef
            
            self.intercept -= (self.learning_rate * dL_by_dB0)
            self.coef -= (self.learning_rate * dL_by_dB1)
            
    def preditct(self,X_test):
        return np.dot(X_test, self.coef) + self.intercept
        

In [12]:
bGd = BatchGradientDescent(learning_rate=0.5,epochs=1000)

In [13]:
bGd.fit(X_train, y_train)

In [14]:
bGd.intercept, bGd.coef

(np.float64(152.01351687661833),
 array([  14.38990585, -173.7235727 ,  491.54898524,  323.91524824,
         -39.32648042, -116.01061213, -194.04077415,  103.38135565,
         451.63448787,   97.57218278]))

In [15]:
y_pred = bGd.preditct(X_test)

In [16]:
y_pred

array([152.26392304, 198.96222354, 127.66111541, 104.59596478,
       265.23062371, 252.09467525, 112.76592254, 115.72549839,
        96.37765691, 187.64845451, 144.9482918 , 172.110596  ,
       178.81497695, 136.51444368, 292.15564227,  87.25795061,
       202.18473262, 149.11155912, 132.30895031, 128.70828962,
       148.38757935, 171.81318343, 150.93593445, 174.47559507,
       127.76388814, 221.82234243, 199.96855698, 101.54518353,
        54.85644772, 237.61948938, 244.2801351 , 112.91877003,
        68.12192242,  96.00468527, 204.32975531, 163.99882781,
       160.95172334, 191.90398957, 113.33794145, 238.46002509,
       141.40211434, 120.45598718, 188.12639096, 186.46474321,
       174.98259299, 143.24561624, 168.80798895, 299.18508813,
       105.40854525, 169.51466009, 254.37509674, 142.60026818,
       151.7158263 , 122.70403085, 191.52875115,  94.27792144,
       129.03875584,  75.96073902, 157.91752518, 156.36603694,
       163.20324594, 160.93274887, 102.3002858 , 227.76

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4534503034722803