In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_regression

In [2]:
X, y = make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [4]:
X = pd.DataFrame(X,columns=['col1','col2'])

In [5]:
X

col1      col2
0   0.447943  1.292961
1  -0.264355 -0.818620
2   0.586783 -0.471925
3  -1.539374 -0.289193
4  -0.699790 -1.798992
..       ...       ...
95 -0.109006  0.181642
96  1.129065 -0.264500
97 -1.177081  1.014628
98 -1.401025 -1.136413
99  0.362856  2.951929

[100 rows x 2 columns]

In [6]:
y

array([  88.10779126,  -72.8400748 ,  -29.76527957, -120.91698515,
       -143.01922602,  224.50316445, -207.59193503,  -66.73888821,
        -16.51443168,   20.0972536 , -177.92469961,  -58.66034482,
        122.64245458,   74.61609888, -131.0657063 ,   31.57759575,
        124.43808993,  -92.00608778, -125.01590377, -102.01082554,
        -17.00707255,   18.47968404, -129.75453177,   93.77050428,
         23.07387717,  -15.02642662,   33.84740374,   37.81190214,
        179.58692803,   62.47698203,  140.01049107,   21.97021023,
         18.44242594,   78.20793329,  -98.06186676,    4.9578472 ,
        242.93606572,   84.97335492,  -99.02537943,  -30.89047207,
        144.6188061 ,   95.8766748 ,   51.87169897,   14.08101393,
        187.22031798,  -77.64689983, -169.55622597,  -41.55623379,
        -12.7769645 , -241.80452287,   -2.04215939,   10.08597781,
        217.61874048, -149.99550775,  -19.24527009,   62.40829666,
       -233.44834702,   69.02729193,   63.53617703,  -66.41162

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 2), (20, 2), (80,), (20,))

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr = LinearRegression()
lr.fit(X,y)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.7335965757039984

### For More that Two class

In [13]:
from sklearn.datasets import load_diabetes
X,y = load_diabetes(return_X_y=True)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [14]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [15]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
r2_score(y_test, y_pred)

0.7225872405273092