In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

In [2]:
X, y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [6]:
class StochasticGradientDescent:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.intercept = None
        self.coef = None
        
    def fit(self,X_train, y_train):
        no_of_row = X_train.shape[0]
        no_of_col = X_train.shape[1]
        
        # 1. Initialize Intercept and Coef
        self.intercept = 0
        self.coef = np.ones(no_of_col)
        
        for epoch in range(self.epochs):
            for ithRow in range(no_of_row):
                
                y_hat = np.dot(self.coef , X_train[ithRow]) + self.intercept
                
                # 2. Calculate Gradient
                dL_by_dB0 = -2 * (y_train[ithRow] - y_hat)
                dL_by_dB1 = -2 * np.dot((y_train[ithRow] - y_hat), X_train[ithRow])
                
                # 3. Update Intercept and Coef
                self.intercept -= (self.learning_rate * dL_by_dB0)
                self.coef -= (self.learning_rate * dL_by_dB1)
                
    def preditct(self,y_train):
        return np.dot(y_train, self.coef) + self.intercept

In [7]:
sgd = StochasticGradientDescent(learning_rate=0.01,epochs=100)

In [8]:
sgd.fit(X_train, y_train)

In [9]:
y_pred = sgd.preditct(X_test)
y_pred

array([157.42131344, 200.6228484 , 135.36459276, 109.75251978,
       263.72325589, 252.29690527, 115.29418752, 119.04111068,
        99.26138155, 190.83365266, 153.70953558, 177.05531317,
       185.1121757 , 144.27800613, 285.38228228,  92.4159353 ,
       200.90274921, 150.40791891, 138.44382717, 136.47481423,
       147.67783159, 180.62075955, 159.47343484, 179.79961109,
       131.59504185, 225.32755726, 203.77716498, 111.14214088,
        60.16402305, 243.14123073, 245.52864957, 118.78455251,
        72.96744045, 103.8034718 , 207.11551716, 168.22981617,
       167.44594125, 197.3666809 , 117.8810594 , 242.19883715,
       143.71602638, 126.5973731 , 190.22807147, 190.63495831,
       177.93522013, 147.27043479, 175.21759006, 297.51259437,
       113.23443195, 179.30787804, 254.3421932 , 142.75766014,
       153.43625368, 135.29054599, 195.57613871, 104.27933838,
       141.51012971,  82.90844603, 163.1284834 , 156.13165397,
       167.78713846, 168.27229661, 108.90154726, 225.62

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4505235983992866