In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../../Data/covid_toy.csv")
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
X_train

(80, 5) (20, 5) (80,) (20,)


age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

# 1. Fever -> Imputation

In [9]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer()
X_train_fever = impute.fit_transform(X_train[['fever']])
X_test_fever = impute.transform(X_test[['fever']])

In [15]:
np.isnan(X_train_fever).sum()

0

# 2. Age, Fever -> ScalingM

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_fever_sca = scaler.fit_transform(X_train_fever)
X_test_fever_sca = scaler.transform(X_test_fever)
X_train_fever_sca

array([[ 0.        ],
       [-0.52164053],
       [-0.52164053],
       [-0.52164053],
       [ 1.04328106],
       [ 1.04328106],
       [ 0.52164053],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [-1.56492159],
       [ 1.56492159],
       [ 1.04328106],
       [ 1.56492159],
       [-0.52164053],
       [ 0.        ],
       [ 1.56492159],
       [ 0.52164053],
       [ 0.52164053],
       [ 1.04328106],
       [ 1.56492159],
       [ 0.52164053],
       [ 0.        ],
       [ 1.56492159],
       [ 0.52164053],
       [ 0.        ],
       [-1.04328106],
       [ 0.        ],
       [ 1.56492159],
       [ 0.52164053],
       [-0.52164053],
       [-1.56492159],
       [-1.56492159],
       [ 0.        ],
       [-0.52164053],
       [-0.52164053],
       [ 0.        ],
       [ 1.56492159],
       [ 0.        ],
       [ 1.04328106],
       [ 0.        ],
       [-1.56492159],
       [-1.04328106],
       [-1.04328106],
       [ 0.        ],
       [-1

In [17]:
scaler = StandardScaler()
X_train_age_sca = scaler.fit_transform(X_train[['age']])
X_test_age_sca = scaler.transform(X_test[['age']])
X_train_age_sca

array([[ 1.56614097],
       [-1.55894504],
       [-0.98327131],
       [-0.65431488],
       [ 1.23718454],
       [ 1.11382589],
       [ 0.25031528],
       [ 0.33255438],
       [ 0.86710857],
       [ 1.64838007],
       [ 0.90822812],
       [-1.02439086],
       [-1.10662996],
       [-1.10662996],
       [-0.65431488],
       [ 1.68949962],
       [ 0.33255438],
       [ 1.07270633],
       [ 1.60726052],
       [ 1.07270633],
       [ 0.04471751],
       [ 1.2783041 ],
       [-0.94215175],
       [-1.27110817],
       [-0.40759757],
       [-0.03752159],
       [ 0.90822812],
       [-0.81879309],
       [ 0.53815215],
       [ 0.86710857],
       [-1.22998862],
       [-0.48983667],
       [-0.1197607 ],
       [ 0.25031528],
       [-0.98327131],
       [-1.31222773],
       [-1.18886907],
       [-0.03752159],
       [-0.2019998 ],
       [ 0.12695662],
       [ 1.15494544],
       [-1.35334728],
       [ 0.70263036],
       [-0.85991265],
       [-0.98327131],
       [ 0

# 3. City. Gender -> OHE

In [18]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [19]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [21]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.transform(X_test[['gender','city']])
X_train_gender_city

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0,

# 4. cough -> Ordinal Encoding

In [22]:
X_train['cough'].value_counts()

cough
Mild      48
Strong    32
Name: count, dtype: int64

In [24]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],

# 5. has_covid -> Label Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_encod = le.fit_transform(y_train)
y_test_encod = le.fit_transform(y_test)

In [26]:
y_train_encod

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1])

# Concatenate all

In [28]:
X_train_cat = np.concatenate((X_train_fever_sca, X_train_age_sca, X_train_gender_city, X_train_cough), axis=1)
X_test_cat = np.concatenate((X_test_fever_sca, X_test_age_sca, X_test_gender_city, X_test_cough), axis=1)
X_train_cat

array([[ 0.        ,  1.56614097,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.52164053, -1.55894504,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ],
       [-0.52164053, -0.98327131,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ],
       [-0.52164053, -0.65431488,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 1.04328106,  1.23718454,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 1.04328106,  1.11382589,  1.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.52164053,  0.25031528,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.33255438,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.        ,  0.86710857,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.6483