# 1. Create numpy

In [121]:
import numpy as np

#1D
a = np.array([1,2,3,4])

#2D
b = np.array([[1,2,3],[4,5,6]])

#3D
c = np.array(
[ [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]]
)

In [122]:
# dtype set
np.array([1,2,3],dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [123]:
# range 
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [124]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Shape change

In [125]:
a

array([1, 2, 3, 4])

In [126]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

# one and zeros and random


In [127]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [128]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.random.random((4,2))

array([[0.66383774, 0.58573026],
       [0.87946178, 0.78688692],
       [0.02247016, 0.93574503],
       [0.51023219, 0.4183328 ]])

# Linespace

In [130]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [131]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

# identity mat

In [132]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attribute

In [133]:
np.arange(4, dtype=np.int32)

array([0, 1, 2, 3])

In [134]:
np.arange(6, dtype=np.float32).reshape(3,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)

In [135]:
x = np.arange(8,dtype=np.int32).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [136]:
# shape
x.shape

(2, 2, 2)

In [137]:
# dimension
x.ndim

3

In [138]:
# size
x.size

8

In [139]:
# type
x.dtype

dtype('int32')

In [140]:
# change type
x.astype(np.float32)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

In [141]:
b1 = np.arange(12,18,dtype=np.float32).reshape(2,3)
b1

array([[12., 13., 14.],
       [15., 16., 17.]], dtype=float32)

In [142]:
b

array([[1, 2, 3],
       [4, 5, 6]])

# Matrix Operation

In [143]:
# scalar multiplication
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [144]:
# element wise power
b ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [145]:
# element wise check
b == 5

array([[False, False, False],
       [False,  True, False]])

In [146]:
# element wise multiplication
b * b1

array([[ 12.,  26.,  42.],
       [ 60.,  80., 102.]])

# Array function

In [147]:
arr = (np.random.random(6).reshape(2,3)) * 25
arr

array([[24.61382059, 19.03448012, 15.09896238],
       [19.337943  , 20.63688168, 19.64099772]])

In [148]:
np.round(arr)

array([[25., 19., 15.],
       [19., 21., 20.]])

In [149]:
np.ceil(arr)

array([[25., 20., 16.],
       [20., 21., 20.]])

In [150]:
np.floor(arr)

array([[24., 19., 15.],
       [19., 20., 19.]])

In [151]:
np.min(arr)

15.098962384712111

In [152]:
np.max(arr)

24.613820594085674

In [153]:
np.sum(arr)

118.36308549952959

In [154]:
np.prod(arr)

55447893.131509736

In [155]:
arr

array([[24.61382059, 19.03448012, 15.09896238],
       [19.337943  , 20.63688168, 19.64099772]])

# Column wise (axis = 0)

In [156]:
np.max(arr , axis=0)

array([24.61382059, 20.63688168, 19.64099772])

# Row wise (axis = 1)

In [157]:
np.max(arr, axis=1)

array([24.61382059, 20.63688168])

# Statistical function

In [158]:
np.mean(arr, axis=0)

array([21.9758818 , 19.8356809 , 17.36998005])

In [159]:
np.median(arr, axis=0)

array([21.9758818 , 19.8356809 , 17.36998005])

In [160]:
np.std(arr, axis=1)

array([3.90370005, 0.55486422])

In [161]:
np.var(arr, axis=0)

array([6.9587211 , 0.64192269, 5.15752126])

# math function

In [162]:
arr

array([[24.61382059, 19.03448012, 15.09896238],
       [19.337943  , 20.63688168, 19.64099772]])

In [163]:
np.sin(arr)

array([[-0.49594315,  0.18387203,  0.57204825],
       [ 0.46920214,  0.97664895,  0.71136734]])

In [164]:
np.log(arr)

array([[3.2033081 , 2.94625208, 2.71462603],
       [2.96206912, 3.02707985, 2.9776191 ]])

# matrix dot product

In [185]:
arr2 = (np.random.random(12).reshape(3,4)) * 25
arr2

array([[12.13225966, 23.11011323, 13.22535506, 12.96431409],
       [ 5.55385713,  7.49257445, 15.079931  , 23.33120129],
       [18.12527429, 20.88632114, 22.77234863, 22.21813569]])

In [166]:
np.dot(arr, arr2)

array([[ 643.23210743, 1165.12106958,  532.29251843,  975.4394894 ],
       [ 726.99754397, 1237.13354341,  534.45479267,  992.10671843]])

# Indexing

In [167]:
# 1D
a

array([1, 2, 3, 4])

In [168]:
a[2]

3

In [169]:
# 2D
arr2

array([[ 3.58753195, 14.31282357,  6.97910752, 16.04135433],
       [15.57890538, 23.52071068, 16.84600127, 17.78957846],
       [17.11328688, 24.18201257,  2.63959474, 16.02660422]])

In [170]:
arr2[2,3]

16.02660422092958

In [171]:
# 3D
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [172]:
c[1,1,0]

10

# Slicing

In [173]:
a[1:3]

array([2, 3])

In [186]:
arr2

array([[12.13225966, 23.11011323, 13.22535506, 12.96431409],
       [ 5.55385713,  7.49257445, 15.079931  , 23.33120129],
       [18.12527429, 20.88632114, 22.77234863, 22.21813569]])

In [187]:
arr2[1:3 , 2:4]

array([[15.079931  , 23.33120129],
       [22.77234863, 22.21813569]])

In [191]:
arr2[[1,2]]   # arr2[[1,2], :]

array([[ 5.55385713,  7.49257445, 15.079931  , 23.33120129],
       [18.12527429, 20.88632114, 22.77234863, 22.21813569]])

In [176]:
c[0:1, 1:3, 0:2]

array([[[4, 5]]])

 # Transpose

In [177]:
arr2.T

array([[ 3.58753195, 15.57890538, 17.11328688],
       [14.31282357, 23.52071068, 24.18201257],
       [ 6.97910752, 16.84600127,  2.63959474],
       [16.04135433, 17.78957846, 16.02660422]])

# 1D Convert

In [178]:
arr2.ravel()

array([ 3.58753195, 14.31282357,  6.97910752, 16.04135433, 15.57890538,
       23.52071068, 16.84600127, 17.78957846, 17.11328688, 24.18201257,
        2.63959474, 16.02660422])

# hstack

In [179]:
arr1 = (np.random.random(6).reshape(3,2)) * 25
arr1

array([[ 0.60724322, 23.63773119],
       [ 0.60970509, 15.05263437],
       [14.42780696,  6.09005961]])

In [180]:
arr2 = (np.random.random(6).reshape(3,2)) * 25
arr2

array([[24.92792414,  7.65303811],
       [11.29373214, 19.66937464],
       [ 6.34494788,  5.0924186 ]])

In [181]:
new_arr = np.hstack((arr1, arr2))
new_arr

array([[ 0.60724322, 23.63773119, 24.92792414,  7.65303811],
       [ 0.60970509, 15.05263437, 11.29373214, 19.66937464],
       [14.42780696,  6.09005961,  6.34494788,  5.0924186 ]])

# hsplit

In [182]:
np.hsplit(new_arr, 2)

[array([[ 0.60724322, 23.63773119],
        [ 0.60970509, 15.05263437],
        [14.42780696,  6.09005961]]),
 array([[24.92792414,  7.65303811],
        [11.29373214, 19.66937464],
        [ 6.34494788,  5.0924186 ]])]

# vstack

In [183]:
new_arr = np.vstack((arr1, arr2))
new_arr

array([[ 0.60724322, 23.63773119],
       [ 0.60970509, 15.05263437],
       [14.42780696,  6.09005961],
       [24.92792414,  7.65303811],
       [11.29373214, 19.66937464],
       [ 6.34494788,  5.0924186 ]])

# vsplit

In [184]:
np.vsplit(new_arr, 3)

[array([[ 0.60724322, 23.63773119],
        [ 0.60970509, 15.05263437]]),
 array([[14.42780696,  6.09005961],
        [24.92792414,  7.65303811]]),
 array([[11.29373214, 19.66937464],
        [ 6.34494788,  5.0924186 ]])]