# 1. Create numpy

In [1]:
import numpy as np

#1D
a = np.array([1,2,3,4])

#2D
b = np.array([[1,2,3],[4,5,6]])

#3D
c = np.array(
[ [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]]
)

In [2]:
# dtype set
np.array([1,2,3],dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [3]:
# range 
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [4]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Shape change

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

# one and zeros and random


In [7]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.random.random((4,2))

array([[0.08306055, 0.53420755],
       [0.62848028, 0.57485838],
       [0.65343512, 0.49554639],
       [0.95606441, 0.98792377]])

# Linespace

In [10]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

# identity mat

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attribute

In [13]:
np.arange(4, dtype=np.int32)

array([0, 1, 2, 3], dtype=int32)

In [14]:
np.arange(6, dtype=np.float32).reshape(3,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)

In [15]:
x = np.arange(8,dtype=np.int32).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [16]:
# shape
x.shape

(2, 2, 2)

In [17]:
# dimension
x.ndim

3

In [18]:
# size
x.size

8

In [19]:
# type
x.dtype

dtype('int32')

In [20]:
# change type
x.astype(np.float32)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

In [21]:
b1 = np.arange(12,18,dtype=np.float32).reshape(2,3)
b1

array([[12., 13., 14.],
       [15., 16., 17.]], dtype=float32)

In [67]:
b2 = np.arange(12,42,dtype=np.float32).reshape(6,5)
b2

array([[12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31.],
       [32., 33., 34., 35., 36.],
       [37., 38., 39., 40., 41.]], dtype=float32)

# Matrix Operation

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# scalar multiplication
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [24]:
# element wise power
b ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [25]:
# element wise check
b == 5

array([[False, False, False],
       [False,  True, False]])

In [26]:
# element wise multiplication
b * b1

array([[ 12.,  26.,  42.],
       [ 60.,  80., 102.]])

# Array function

In [27]:
arr = (np.random.random(6).reshape(2,3)) * 25
arr

array([[15.58542233,  7.72088471, 10.71081361],
       [16.65453436, 11.93949571, 21.10261945]])

In [28]:
np.round(arr)

array([[16.,  8., 11.],
       [17., 12., 21.]])

In [29]:
np.ceil(arr)

array([[16.,  8., 11.],
       [17., 12., 22.]])

In [30]:
np.floor(arr)

array([[15.,  7., 10.],
       [16., 11., 21.]])

In [31]:
np.min(arr)

np.float64(7.720884708368059)

In [32]:
np.max(arr)

np.float64(21.102619449980505)

In [33]:
np.sum(arr)

np.float64(83.71377016835203)

In [34]:
np.prod(arr)

np.float64(5408327.101500674)

In [35]:
arr

array([[15.58542233,  7.72088471, 10.71081361],
       [16.65453436, 11.93949571, 21.10261945]])

# Column wise (axis = 0)

In [36]:
np.max(arr , axis=0)

array([16.65453436, 11.93949571, 21.10261945])

# Row wise (axis = 1)

In [37]:
np.max(arr, axis=1)

array([15.58542233, 21.10261945])

# Statistical function

In [38]:
np.mean(arr, axis=0)

array([16.11997834,  9.83019021, 15.90671653])

In [39]:
np.median(arr, axis=0)

array([16.11997834,  9.83019021, 15.90671653])

In [40]:
np.std(arr, axis=1)

array([3.24126925, 3.74135874])

In [41]:
np.var(arr, axis=0)

array([ 0.28575013,  4.44916969, 26.99740713])

# math function

In [42]:
arr

array([[15.58542233,  7.72088471, 10.71081361],
       [16.65453436, 11.93949571, 21.10261945]])

In [43]:
np.sin(arr)

array([[ 0.12223448,  0.99115567, -0.95972891],
       [-0.81141619, -0.58661673,  0.77614512]])

In [44]:
np.log(arr)

array([[2.74633601, 2.04392896, 2.37125385],
       [2.81268251, 2.47985187, 3.04939718]])

# matrix dot product

In [45]:
arr2 = (np.random.random(12).reshape(3,4)) * 25
arr2

array([[19.96065439, 17.56840023, 24.3355061 ,  1.01436537],
       [ 3.11400637, 21.78101828,  9.04733226,  8.45099791],
       [20.92768488, 11.75659199, 13.48041337, 24.5948081 ]])

In [46]:
np.dot(arr, arr2)

array([[559.290645  , 567.90233382, 593.51874452, 344.48889854],
       [811.24404018, 800.74278642, 797.78914065, 636.80931177]])

# Indexing

In [47]:
# 1D
a

array([1, 2, 3, 4])

In [48]:
a[2]

np.int64(3)

In [49]:
# 2D
arr2

array([[19.96065439, 17.56840023, 24.3355061 ,  1.01436537],
       [ 3.11400637, 21.78101828,  9.04733226,  8.45099791],
       [20.92768488, 11.75659199, 13.48041337, 24.5948081 ]])

In [50]:
arr2[2,3]

np.float64(24.594808097502916)

In [51]:
# 3D
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
c[1,1,0]

np.int64(10)

# Slicing

In [53]:
# 1D
a[1:3]

array([2, 3])

In [54]:
# 2D
arr2

array([[19.96065439, 17.56840023, 24.3355061 ,  1.01436537],
       [ 3.11400637, 21.78101828,  9.04733226,  8.45099791],
       [20.92768488, 11.75659199, 13.48041337, 24.5948081 ]])

In [55]:
arr2[1:3 , 2:4]

array([[ 9.04733226,  8.45099791],
       [13.48041337, 24.5948081 ]])

In [56]:
arr2[[1,2]]   # arr2[[1,2], :]

array([[ 3.11400637, 21.78101828,  9.04733226,  8.45099791],
       [20.92768488, 11.75659199, 13.48041337, 24.5948081 ]])

In [57]:
c[0:1, 1:3, 0:2]

array([[[4, 5]]])

 # Transpose

In [58]:
arr2.T

array([[19.96065439,  3.11400637, 20.92768488],
       [17.56840023, 21.78101828, 11.75659199],
       [24.3355061 ,  9.04733226, 13.48041337],
       [ 1.01436537,  8.45099791, 24.5948081 ]])

# 1D Convert

In [59]:
arr2.ravel()

array([19.96065439, 17.56840023, 24.3355061 ,  1.01436537,  3.11400637,
       21.78101828,  9.04733226,  8.45099791, 20.92768488, 11.75659199,
       13.48041337, 24.5948081 ])

# hstack

In [60]:
arr1 = (np.random.random(6).reshape(3,2)) * 25
arr1

array([[21.7517993 , 14.2824449 ],
       [ 1.12002726,  3.71221047],
       [ 0.22092178,  2.35648868]])

In [61]:
arr2 = (np.random.random(6).reshape(3,2)) * 25
arr2

array([[21.67955198, 24.59305725],
       [ 2.88262322,  0.61517501],
       [23.33134424, 11.97203467]])

In [62]:
new_arr = np.hstack((arr1, arr2))
new_arr

array([[21.7517993 , 14.2824449 , 21.67955198, 24.59305725],
       [ 1.12002726,  3.71221047,  2.88262322,  0.61517501],
       [ 0.22092178,  2.35648868, 23.33134424, 11.97203467]])

# hsplit

In [63]:
np.hsplit(new_arr, 2)

[array([[21.7517993 , 14.2824449 ],
        [ 1.12002726,  3.71221047],
        [ 0.22092178,  2.35648868]]),
 array([[21.67955198, 24.59305725],
        [ 2.88262322,  0.61517501],
        [23.33134424, 11.97203467]])]

# vstack

In [64]:
new_arr = np.vstack((arr1, arr2))
new_arr

array([[21.7517993 , 14.2824449 ],
       [ 1.12002726,  3.71221047],
       [ 0.22092178,  2.35648868],
       [21.67955198, 24.59305725],
       [ 2.88262322,  0.61517501],
       [23.33134424, 11.97203467]])

# vsplit

In [65]:
np.vsplit(new_arr, 3)

[array([[21.7517993 , 14.2824449 ],
        [ 1.12002726,  3.71221047]]),
 array([[ 0.22092178,  2.35648868],
        [21.67955198, 24.59305725]]),
 array([[ 2.88262322,  0.61517501],
        [23.33134424, 11.97203467]])]