In [39]:
import numpy as np

In [40]:
arr = (np.random.random(24) * 25).reshape(4,6)
arr

array([[15.26333792, 17.21707399, 12.4752108 , 23.05756855, 23.14315921,
        10.59486843],
       [ 8.08780817, 16.90820646, 10.26721885,  3.52200865, 23.09249228,
        11.09007278],
       [12.51084288, 20.51112317, 24.24581682, 15.53991684, 12.92790427,
        15.10289522],
       [10.16865866,  3.84846425, 23.66906902, 14.54459946, 14.85377956,
        24.43539696]])

##### 1.Extract the first row

In [41]:
arr[0,:]

array([15.26333792, 17.21707399, 12.4752108 , 23.05756855, 23.14315921,
       10.59486843])

##### 2.Extract the first column

In [42]:
arr[:,0]

array([15.26333792,  8.08780817, 12.51084288, 10.16865866])

##### 3.Extract the last row

In [43]:
arr[-1,:]

array([10.16865866,  3.84846425, 23.66906902, 14.54459946, 14.85377956,
       24.43539696])

##### 4.Extract the last column

In [44]:
arr[:, -1]

array([10.59486843, 11.09007278, 15.10289522, 24.43539696])

##### 5.Extract a submatrix (first 2 rows and 3 columns)

In [45]:
arr[:2,:3]

array([[15.26333792, 17.21707399, 12.4752108 ],
       [ 8.08780817, 16.90820646, 10.26721885]])

##### 6. Reverse the rows of a 2D array

In [46]:
arr[::-1, :]

array([[10.16865866,  3.84846425, 23.66906902, 14.54459946, 14.85377956,
        24.43539696],
       [12.51084288, 20.51112317, 24.24581682, 15.53991684, 12.92790427,
        15.10289522],
       [ 8.08780817, 16.90820646, 10.26721885,  3.52200865, 23.09249228,
        11.09007278],
       [15.26333792, 17.21707399, 12.4752108 , 23.05756855, 23.14315921,
        10.59486843]])

# Boolean Indexing

In [47]:
arr > 10

array([[ True,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True]])

In [48]:
arr[ arr > 10 ]

array([15.26333792, 17.21707399, 12.4752108 , 23.05756855, 23.14315921,
       10.59486843, 16.90820646, 10.26721885, 23.09249228, 11.09007278,
       12.51084288, 20.51112317, 24.24581682, 15.53991684, 12.92790427,
       15.10289522, 10.16865866, 23.66906902, 14.54459946, 14.85377956,
       24.43539696])

In [65]:
arr2 = np.random.randint(1,25, (4,6))
arr2

array([[ 3,  7,  1, 20, 15,  9],
       [12, 22, 24, 15, 22,  1],
       [21, 16,  6, 20, 20, 18],
       [22, 12,  9, 12, 10, 17]])

In [66]:
arr2 % 2 == 0

array([[False, False, False,  True, False, False],
       [ True,  True,  True, False,  True, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True, False]])

In [67]:
(arr2 % 2 == 0) & (arr2 > 10)

array([[False, False, False,  True, False, False],
       [ True,  True,  True, False,  True, False],
       [False,  True, False,  True,  True,  True],
       [ True,  True, False,  True, False, False]])

In [68]:
arr2[ arr2 % 2 == 0 ]

array([20, 12, 22, 24, 22, 16,  6, 20, 20, 18, 22, 12, 12, 10])

In [69]:
arr2[ (arr2 % 2 == 0) & (arr2 > 10) ]

array([20, 12, 22, 24, 22, 16, 20, 20, 18, 22, 12, 12])

# Missing Value Check

In [72]:
misArr = np.array([[1,np.nan],[3,4]])
misArr

array([[ 1., nan],
       [ 3.,  4.]])

In [73]:
np.isnan(misArr)

array([[False,  True],
       [False, False]])

In [74]:
misArr[ np.isnan(misArr) ]

array([nan])

In [75]:
misArr[ ~ np.isnan(misArr) ]

array([1., 3., 4.])

# Random Number

In [70]:
np.random.rand(2,3)

array([[0.69092982, 0.33564443, 0.01790185],
       [0.66584058, 0.04633107, 0.49155411]])

In [71]:
np.random.randint(1,10 , (2,3))

array([[7, 1, 2],
       [8, 5, 2]])

In [62]:
np.random.randn(3,3)

array([[ 0.51395313, -1.15195171,  0.29816171],
       [-2.52133179,  0.87689032, -0.72541254],
       [-0.81686152,  0.30670051,  0.22476576]])

In [64]:
np.random.uniform(1, 5, (2,2))

array([[1.61106884, 1.98788207],
       [3.49922804, 3.67902836]])

# Broadcasting

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [78]:
arr1 = np.random.randint(1,20, (3,4))
arr2 = np.random.randint(1,20, (4))
arr1 + arr2

array([[ 9,  7, 19,  6],
       [16,  7,  7, 15],
       [15, 25, 20,  3]])

In [79]:
arr1 = np.random.randint(1,20, (3,4))
arr2 = np.random.randint(1,20, (3))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [80]:
arr1 = np.random.randint(1,20, (1,3))
arr2 = np.random.randint(1,20, (4,3))
arr1 + arr2

array([[ 6, 34, 21],
       [18, 29, 18],
       [16, 36, 18],
       [10, 19, 16]])

In [81]:
arr1 = np.random.randint(1,20, (1))
arr2 = np.random.randint(1,20, (2,2))
arr1 + arr2

array([[37, 23],
       [36, 29]])

In [82]:
arr1 = np.random.randint(1,20, (3,4))
arr2 = np.random.randint(1,20, (4,3))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [83]:
arr1 = np.random.randint(1,20, (4,4))
arr2 = np.random.randint(1,20, (2,2))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 